#To be run via -Dspring.profiles.active=prod for production or no argument otherwise
# ** Remember to install rxtx.jar as per http://smslib.org/doc/installation/#Java_Communications_Library to make the smslib library working
#    For windows 64 bits : http://jlog.org/rxtx-win.html or http://fizzed.com/oss/rxtx-for-java
#    If using a JDK, copy also the files RXTX files to %JDK_HOME%/lib/ext and %JDK_HOME%/bin
#    Execution : java - jar service-1.0.jar

#Server
server.port: 8090

#Database
database:
    host: localhost
    port: 9042
    keyspace: picontroller

#SIM card
sim:
    gatewayManufacturer: Dell
    gatewayName: #DW5550
    gatewayPort: COM3
    gatewayBaudRate: 921600
    smscNumber: #Not needed with Bouygues
    simPin: 1903
    forwardToNumber: 

#Webcam
webcam:
    dimension:
        width: 640
        height: 480
    path: C:/tmp/shots/
    facesPath : C:/tmp/shots/faces/
    predictedFacesPath: C:/tmp/shots/predicted/faces/
    predictedImagesPath: C:/tmp/shots/predicted/images/
    faceDetectionClassifierName: haarcascade_frontalface_alt.xml